### POST weather
POST http://localhost:3000/weather
Content-Type: application/json

{
    "id": 3,
    "name": "sunny",
    "minmax": [10,23],
    "date": "2025-10-02"
}
### DELETE weather by id
DELETE http://localhost:3000/weather/1
Content-Type: application/json
### UPDATE weather
PATCH  http://localhost:3000/weather/3
Content-Type: application/json

{
    "id": 3,
    "name": "cloudy",
    "minmax": [10,22],
    "date": "2025-10-01"
}
